pipeline {
  agent any
  environment {
    DOCKER_IMAGE = "your-dockerhub-username/demo-app"
  }
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh 'mvn clean package -DskipTests'
      }
    }
    stage('SonarQube') {
      steps {
        withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
          sh 'mvn sonar:sonar -Dsonar.host.url=http://<SONAR_HOST>:9000 -Dsonar.login=$SONAR_TOKEN'
        }
      }
    }
    stage('Docker Build & Push') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: 'docker-cred', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
            sh 'docker build -t ${DOCKER_IMAGE}:${GIT_COMMIT} .'
            sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
            sh 'docker push ${DOCKER_IMAGE}:${GIT_COMMIT}'
          }
        }
      }
    }
    stage('Update Manifest') {
      steps {
        withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
          sh 'bash scripts/update-manifest.sh ${GIT_COMMIT} $GITHUB_TOKEN'
        }
      }
    }
  }
}
